name: deploy stack

on:
  workflow_call:
    inputs:
      WORKSPACE_NAME:
        description: 'Workspace name'
        required: true
        type: string
        default: 'default'
      AWS_ACCOUNT_ID:
        required: true
        type: string
permissions:
  id-token: write

jobs:
  bootstrap:
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    with:
      WORKSPACE_NAME: "default"
      LAYER: bootstrap
      AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}

  ops:
    needs: [bootstrap]
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    with:
      WORKSPACE_NAME: ${{ inputs.WORKSPACE_NAME }}
      LAYER: ops
      AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}

  app:
    needs: [ops]
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    with:
      WORKSPACE_NAME: ${{ inputs.WORKSPACE_NAME }}
      LAYER: app
      AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}
